apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: pod-annotation-webhook
webhooks:
  - name: webhook-server.ml-workshop.svc
    namespaceSelector:
      matchExpressions:
        - key: applyMLToleration
          operator: In
          values: ["true","yes", "1"]
    clientConfig:
      service:
        name: webhook-server
        namespace: ml-workshop
        path: "/mutate"
      caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURBRENDQWVnQ0NRQ3BZK2Y5WHhaOXVqQU5CZ2txaGtpRzl3MEJBUXNGQURCQ01VQXdQZ1lEVlFRREREZFEKVDJRZ1ZHOXNaWEpoZEdsdmJpQk5kWFJoZEdsdVp5QkJaRzFwYzNOcGIyNGdRMjl1ZEhKdmJHeGxjaUJYWldKbwpiMjlySUVOQk1CNFhEVEl3TURVeU1qQTBNamswTjFvWERUSXdNRFl5TVRBME1qazBOMW93UWpGQU1ENEdBMVVFCkF3dzNVRTlrSUZSdmJHVnlZWFJwYjI0Z1RYVjBZWFJwYm1jZ1FXUnRhWE56YVc5dUlFTnZiblJ5YjJ4c1pYSWcKVjJWaWFHOXZheUJEUVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTVFmbE4wcApHUW9SOTFiWmJuSjlsTWx4QzkrdEE0cEpPUi9zWk5Yb1BsRWMzQ3FxTldMZGZuL3BFL3NCK0FidXg4N0gxaktkCnE5aTIwODcvR0FwMWZQbkR2a2Z3WnBHU2g3UnR1RDZ3UHNNVW9vY1MwcWNWZk42dVZ2RlFHWUxxT2RoVTZ0QmEKMWVEMlhzTks5NWJ1Q0M5MTdTMlBNRS94S2UzTzlkdkx5WGRHMDI3R1ZFU0ljZ2VIRk9QODJhUHErK1N5cVJGNApmTmI3K3JoV0lvbmFoNE9KQThuS3E0YXp4djhGL0tLUnhObzF0dzB5YzloVG5GOEpDc2NVNkJvNTR2V2ljMXNDCkFaQWZSU09sV3FQdFoyTUNiRnU5VlZNOUZUdDVwRUZPd3BkUU95ZEV1KzJiV2hsVVlOSDVlakMvZ2xkZGNqUXcKYnRHZ3VXWHRRZ3ZrVUFVQ0F3RUFBVEFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBcUJKeFNVOUFaNUxYUzYvZQpaZ0NlZWdiSVMxUkxCb2p3b2R6c01oSlFPanFKb1Q3dXoxc09TdVZjM1lKNjRuZ3JERWEzT1hzUFNqNW1ZNUhBCmVNUGJqNjF0THRvSVNPbXVDK0ZEb2NaMmRzQk1haW9ZdmptVEtad2x1UHp3dFJ3Q2NvV25UT2w0R3NHaCtESk4KYk5pY1RPbzVhK1NRakNNemlqVU9BRFFGN3JIdWFoeUpBbmVLdERIZnR5NTI4OWQyd0xrd3AvVDF5UThqR3o0bgoxRG5jVVZxbUdSL3ZROWh2dzduSnhva3V3dU1pY21tdnMrN2lHM3NuOVVpYVorcG1ZbGVvNVNvTHZXMDJRRDZvCkZDS3ZsbllpM2dpTUVadFZvUHh5M0dHZkdURXJWenJ0OVdoTmkxUzVyOUUrY3k5NGZ1a0F5M2w1cnNYMmFTVG8KVFRUUndRPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
        scope: "Namespaced"


